language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
env:
  global:
    - TEST_PATH='framework-tests'
    - SYMFONY_DEPRECATIONS_HELPER=weak
  matrix:
    - VERSION=3.4 TEST_REPO='--recurse-submodules https://github.com/Naktibalda/codeception-symfony-tests'
    - VERSION=4 TEST_REPO='https://github.com/Codeception/symfony-demo.git' SUITES=functional,unit
    - VERSION=5 TEST_REPO='-b symfony5 https://github.com/Codeception/symfony-demo.git' SUITES=functional,unit
matrix:
  exclude:
    - php: 7.3
      env: VERSION=3.4 TEST_REPO='--recurse-submodules https://github.com/Naktibalda/codeception-symfony-tests'
    - php: 7.4
      env: VERSION=3.4 TEST_REPO='--recurse-submodules https://github.com/Naktibalda/codeception-symfony-tests'
    - php: 7.0
      env: VERSION=4 TEST_REPO='https://github.com/Codeception/symfony-demo.git' SUITES=functional,unit
    - php: 7.0
      env: VERSION=5 TEST_REPO='-b symfony5 https://github.com/Codeception/symfony-demo.git' SUITES=functional,unit
    - php: 7.1
      env: VERSION=5 TEST_REPO='-b symfony5 https://github.com/Codeception/symfony-demo.git' SUITES=functional,unit
services:
  - mysql
before_install:
  - export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo memory_limit = -1 >> $INI
install:
  - '[[ -z "$CI_USER_TOKEN" ]] || composer config github-oauth.github.com ${CI_USER_TOKEN};'
  - travis_retry composer self-update && composer --version
  - git clone -q --depth=1 $TEST_REPO framework-tests
  - git --git-dir framework-tests/.git log -n 1
  - composer require symfony/finder=~$VERSION --no-update --ignore-platform-reqs
  - composer require symfony/yaml=~$VERSION --no-update --ignore-platform-reqs
  - composer require symfony/console=~$VERSION --no-update --ignore-platform-reqs
  - composer require symfony/event-dispatcher=~$VERSION --no-update --ignore-platform-reqs
  - composer require symfony/css-selector=~$VERSION --no-update --ignore-platform-reqs
  - composer require symfony/dom-crawler=~$VERSION --no-update --ignore-platform-reqs
  - composer require symfony/browser-kit=~$VERSION --no-update --ignore-platform-reqs
  - COMPOSER_MEMORY_LIMIT=-1 composer install
  - COMPOSER_MEMORY_LIMIT=-1 composer update -d framework-tests --no-dev --prefer-dist --no-interaction
before_script:
  - mysql -e "create database symfony_test;"
  - '[[ "$VERSION" != "3.4" ]] || php framework-tests/bin/console doctrine:schema:update --force -n'
  - php ./vendor/bin/codecept build -c $TEST_PATH
script:
  - php ./vendor/bin/codecept run functional -c $TEST_PATH
